apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeants-editor
rules:
# clusters 资源权限
- apiGroups: ["cluster.kubeants.io"]
  resources: ["clusters"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
 
# roletemplates 资源权限
- apiGroups: ["rbac.kubeants.io"]
  resources: ["roletemplates"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
 
# users 资源权限
- apiGroups: ["user.kubeants.io"]
  resources: ["users"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
 
# userbindings 资源权限
- apiGroups: ["userbinding.kubeants.io"]
  resources: ["userbindings"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
 
# workspaces 资源权限
- apiGroups: ["workspace.kubeants.io"]
  resources: ["workspaces"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]

