apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: busybox-ts
  name: busybox-ts
  namespace: public1
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: busybox-ts
        spec:
          restartPolicy: Never
          containers:
            - command:
                - /bin/sh
                - '-c'
                - echo "I am kubeants"
              image: busybox:1.28.4
              imagePullPolicy: IfNotPresent
              name: busybox
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
  schedule: '*/2 * * * *'
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
  suspend: true
