---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ka-console
  namespace: kubeants-system
data:
  default.conf: |-
    server {
        listen 80;
        server_name localhost;
        location /demo/ {
            # 使用 alias 替代 root，直接指向 dist 目录
            alias /usr/share/nginx/html/;  # 注意结尾的斜杠
            index index.html;
            try_files $uri $uri/ /demo/index.html;  # 确保回退到 index.html
        }
        # 可选：处理直接访问根路径的情况
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
        # 新增：反向代理到后端 API
        location /gapi/ {
            proxy_pass http://kubeants-apiserver.kubeants-system:8080; # 替换为实际后端地址
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeants-console
  namespace: kubeants-system
  labels:
    app: kubeants-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeants-console
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubeants-console
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-li19dt
          configMap:
            name: ka-console
            items:
              - key: default.conf
                path: default.conf
            defaultMode: 420
      containers:
        - name: container-y2072s
          image: 'repos.devops.cmft/workbench/kubeants-console:v1.2.6'
          ports:
            - name: http-0
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-li19dt
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

