---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ka-console
  namespace: kubeants-system
data:
  config.json: |-
    {
        "VUE_APP_BASE_API": "/gapi"
    }
  default.conf: |-
    server {
        listen 80;
        server_name localhost;
        
        # 静态资源服务
        location /ka-console {
            alias /usr/share/nginx/html/;
            index index.html;
            try_files $uri $uri/ /ka-console/index.html;
        }
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
        
        # API 代理配置
        location /gapi/ {
            proxy_pass http://kubeants-apiserver.kubeants-system:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # 添加跨域支持
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
            add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
            
            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeants-console
  namespace: kubeants-system
  labels:
    app: kubeants-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeants-console
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubeants-console
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-li19dt
          configMap:
            name: ka-console
            items:
              - key: default.conf
                path: default.conf
              - key: config.json
                path: config.json
            defaultMode: 420
      containers:
        - name: container-y2072s
          image: 'registry.cn-hangzhou.aliyuncs.com/geray/kubeants-console:v1.1.38'
          imagePullPolicy: IfNotPresent
          env:
            - name: VUE_APP_BASE_API
              value: '/gapi'  # 改为相对路径
          ports:
            - name: http-0
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-li19dt
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: volume-li19dt
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeants-console
  name: kubeants-console
  namespace: kubeants-system
spec:
  ports:
  - name: http
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubeants-console
  type: NodePort
