---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: netshoot
  namespace: kubeants-system
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
        - name: net
          image: 'registry.cn-hangzhou.aliyuncs.com/geray/netshoot:v1.0'
          command:
            - sleep
          args:
            - '100000'
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
  namespace: kubeants-system
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: net
          image: 'busybox:1.28.4'
          command:
            - sleep
          args:
            - '100000'
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi

